### ISSUE TITLE
Center align icons UPGRADE and DOWNGRADE icon

### ISSUE THREAD

**Issue by bigint** [Ricochet-Exchange/ricochet-frontend#182] opened 2022-01-05 03:59 UTC
![Screenshot 2022-01-05 at 9 28 54 AM](https://user-images.githubusercontent.com/69431456/148158596-9528091c-3a82-414a-8c41-56b2d4c1b815.png)

**Comment by vaibhavgeek** [comment] 2022-01-10 15:58
@bigint / @mikeghen This seems like an issue from my work, please assign this to me.

**Comment by vaibhavgeek** [comment] 2022-01-11 15:14
Screenshot of centered icons 
<img width="1512" alt="Screenshot 2022-01-11 at 8 43 46 PM" src="https://user-images.githubusercontent.com/1227925/148969080-167c83a2-6290-40b9-95df-520b76d7e0d9.png">

**Comment by vaibhavgeek** [comment] 2022-01-11 15:47
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/195

**Comment by elvijsTDL** [comment] 2022-01-16 12:33
@vaibhavgeek Might be a little bit nitpicky, but it would be great to see the Currency and the upgrade/downgrade buttons be right aligned to the headers like rest of the collumns , I think it would give a more polished look , and looks like the lines for some of the collumns are gone too

**Comment by vaibhavgeek** [comment] 2022-01-16 13:43
@elvijsTDL The lines for some of the columns did not exist by design in the first place, the idea was to separate different sections of the table.

**Comment by vaibhavgeek** [comment] 2022-01-17 07:10
@elvijsTDL I have right aligned the buttons. 

<img width="1427" alt="Screenshot 2022-01-17 at 12 38 12 PM" src="https://user-images.githubusercontent.com/1227925/149723318-53699bf4-937a-46db-9227-e830c1bd33ae.png">

**Comment by mikeghen** [comment] 2022-01-26 13:28
Is this done?

**Comment by vaibhavgeek** [comment] 2022-01-26 13:30
Yes, @mikeghen , it has been approved and merged as well

**Closed** 2022-01-31 20:21 UTC
