### ISSUE TITLE
RexBank and RexVault issues

### ISSUE THREAD

**Issue by elvijsTDL** [Ricochet-Exchange/ricochet-frontend#196] opened 2022-01-11 20:44 UTC
rexVault button not visible before opening rexBank
<img width="187" alt="Screenshot 2022-01-11 at 22 31 42" src="https://user-images.githubusercontent.com/77115130/149016797-4a1f80e4-c3d2-41b3-ad55-c55c33756246.png">

  rexVault button appears under “Tutorial” hyperlink  
<img width="179" alt="Screenshot 2022-01-11 at 22 32 26" src="https://user-images.githubusercontent.com/77115130/149016896-bdcd8273-adfb-4825-8fd6-b88200ed25e8.png">

withdraw / deposit  and borrow / repay buttons not aligned to the same right side position  
![image](https://user-images.githubusercontent.com/77115130/149017160-d1d8e9d8-3864-4a52-a5f9-50dd1a8eed9b.png)

Colleterazation and liquidation price titles have unnecessary large spacing in-between the numbers and the title
<img width="565" alt="Screenshot 2022-01-11 at 22 34 11" src="https://user-images.githubusercontent.com/77115130/149017231-e23d7e3b-2fb3-44c3-879e-6c0a1e992ddc.png">

  Users can input negative numbers and into the withdraw/deposit/borrow/repay fields and the button becomes “enabled”  
<img width="390" alt="Screenshot 2022-01-11 at 22 34 36" src="https://user-images.githubusercontent.com/77115130/149017339-273a0e55-b82e-477f-94fe-56ce5d0c37e0.png">

All button texts are lowercase  
<img width="476" alt="Screenshot 2022-01-11 at 22 35 06" src="https://user-images.githubusercontent.com/77115130/149017414-5f9e6406-b7f6-4b9f-a825-52a9a36e6a8c.png">

Available to borrow shows total amount that user could borrow using their collateral, not the one actually available in the bank  

Repay button always opens with “give allowance” button

https://user-images.githubusercontent.com/77115130/149018406-2d32c8fe-800b-4eaf-b5c0-8227a437511a.mov

 Visiting the vault page directly does not load users vaults
https://user-images.githubusercontent.com/77115130/149018108-2b648d91-ce3e-4c81-a8c4-9864ccb5738a.mov

Sign in with web3 button is white on white  
<img width="331" alt="Screenshot 2022-01-11 at 22 38 02" src="https://user-images.githubusercontent.com/77115130/149017763-d33b87cc-4c3e-4f3b-8624-5619ba5acc5d.png">

Transaction error kind of breaks the UI   in vaults page
<img width="550" alt="Screenshot 2022-01-11 at 22 39 05" src="https://user-images.githubusercontent.com/77115130/149017933-7df59420-d58c-485e-8949-6d9fa48b9a57.png">

Repay max button can be used and it allows user to click on repay button even if the user has not given allowance yet
<img width="974" alt="Screenshot 2022-01-11 at 22 39 35" src="https://user-images.githubusercontent.com/77115130/149018007-5dfd6d46-da83-4398-b122-94a6c647fdc7.png">

  Infinite loading spinner is shown to the user and the vault buttons are disabled even after the borrowing transaction has been confirmed

 Enchantment:   Add Polygonscan hyperlink for the bank in the vault page

**Comment by elvijsTDL** [comment] 2022-01-11 20:44
I will work on these

**Comment by sunnyjaycer** [comment] 2022-01-13 15:33
Great attention to detail @elvijsTDL. Added bounty comp

**Comment by josealonso** [comment] 2022-01-23 00:55
@sunnyjaycer, can you add a *help wanted* label, since @elvijsTDL cannot keep working on Ricochet issues during January and February.

**Comment by sunnyjaycer** [comment] 2022-01-24 00:02
done @josealonso

**Comment by lucasz-hu** [comment] 2022-01-28 21:25
Working on this

**Comment by josealonso** [comment] 2022-01-31 20:17
@lucasz-hu, does these changes apply to the new design recently proposed by @serotoninexperience ?

**Comment by lucasz-hu** [comment] 2022-02-03 01:28
@josealonso Sorry for slow response, I'm on vacation for CNY so I'm not always available. 

I believe so. The recent layout changes didn't seem to change the RexBank/RexVault pages.

Also BTW, I will be back on the weekend. So if someone wants to take over, feel free to.

**Comment by Seroxdesign** [comment] 2022-02-04 03:46
@josealonso I made some changes to the vault in #301 I will work on all these as well.

**Comment by Seroxdesign** [comment] 2022-02-05 05:17
https://github.com/Ricochet-Exchange/ricochet-frontend/pull/302

Fixes in this PR:

Gave the sign in a background color to distinguish it.
![new log in](https://user-images.githubusercontent.com/69639595/152629640-46c10f75-23ba-4c6d-9656-cec41029b708.jpg)

Disabled all buttons on repay until the user gives allowance
![allowence](https://user-images.githubusercontent.com/69639595/152629655-378754e1-fd2e-4941-99c1-a60ed8433986.png)

Changed text in vault to push user into opening their bank for the vault to load, this means whether or not they've used the platform it still makes sense:
![rex vault change](https://user-images.githubusercontent.com/69639595/152629668-a4646c3f-7476-4a64-8a47-9afa821660f2.jpg)

Added Ricochet contract link, now user can click on the purple text at the top right to view the contract on polyscan
![rex link](https://user-images.githubusercontent.com/69639595/152629684-76608b32-d086-4237-8900-bd60ad3b2e11.png)

Reduced the size of the numbers and the padding between the number and the text above it:
![postitibe](https://user-images.githubusercontent.com/69639595/152629705-8ec11d81-cc35-40ae-a622-f582a26f3f81.jpg)

**Comment by Seroxdesign** [comment] 2022-02-05 15:44
Also users can't use negative numbers in the input field

**Comment by Seroxdesign** [comment] 2022-02-05 21:40
All issues except the total available to borrow have been resolved. 

I don't want to touch the store

**Comment by Seroxdesign** [comment] 2022-02-08 23:23
Progress:

1. rexVault button not visible before opening rexBank:   Bank needs to be opened first, opening vault:   SOLVED
2.    rexVault button appears under “Tutorial” hyperlink  :  SOLVED
3. withdraw / deposit and borrow / repay buttons not aligned to the same right side position  :  SOLVED
4. Colleterazation and liquidation price titles have unnecessary large spacing in-between the numbers and the title: SOLVED
5.   Users can input negative numbers and into the withdraw/deposit/borrow/repay fields and the button “enabled”  : SOLVED
6. All button texts are lowercase  : SOLVED
7. Repay button always opens with “give allowance” button: SOLVED
8. Sign in with web3 button is white on white:  SOLVED
9. Transaction error kind of breaks the UI   in vaults page:  SOLVED
10.  Repay max button can be used, it allows user to click on repay button even if the user has not given allowance: SOLVED
11.   Infinite loading spinner is shown to the user and the vault buttons are disabled even after the borrowing transaction has been confirmed: SOLVED
12.  PR pending review now    LINK: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/302

Enchantment:  Link to bank added in VaultPage

Left unsolved:     Visiting the vault page directly does not load users vaults
https://user-images.githubusercontent.com/77115130/149018108-2b648d91-ce3e-4c81-a8c4-9864ccb5738a.mov
      _A solution for this is in the working, it has been opened as a NEW ISSUE_: https://github.com/Ricochet-Exchange/ricochet-frontend/issues/339

**Comment by Seroxdesign** [comment] 2022-02-10 00:51
Reworking this.

**Comment by josealonso** [comment] 2022-02-14 11:11
@Seroxdesign, I don't understand why you closed your own PR.

**Comment by Seroxdesign** [comment] 2022-02-14 13:22
Solution wasn't done right and this branch had too many issues. 

Reworking it

**Comment by mikeghen** [comment] 2022-02-14 15:43
it was looking good, looking forward to another PR with this in it :+1:

**Comment by Seroxdesign** [comment] 2022-02-16 22:37
This issue can be closed now.

PR: https://github.com/Ricochet-Exchange/ricochet-frontend/pull/399

**Comment by josealonso** [comment] 2022-02-16 23:59
> This issue can be closed now.
> 
> PR: #399

Thank you for your message. Try to do it for your next PRs. Closing it now.

**Closed by josealonso** 2022-02-16 23:59 UTC
Labels: enhancement, $500 bounty
